# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0038_auto_20160923_0342'),
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityvote',
            name='been_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='activityvote',
            unique_together=set([('activity', 'user')]),
        ),
    ]
