# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20160923_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityvote',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_activityvote_activity', to='activity.Activity'),
        ),
    ]
